16 - Plano de Custos
fga-eps-mds/2023-1-Alectrion-DOC pull request #20
Opened 2023-04-25 03:20 UTC by mibasFerraz

Criacao do arquivo de plano de custos assim como a alteração do path
Falta: saber quando entregaremos o mvp

2023-04-25 10:53 UTC, AlineLermen requested changes

2023-04-25 10:53 UTC, AlineLermen commented on docs/plano-custos.md
> +Considerando as estimativas de custos acima calculadas e uma margem de 10%, o orçamento total para o projeto em 16 semanas é:
Aqui seriam 17 semanas de projeto, certo?
```suggestion
Considerando as estimativas de custos acima calculadas e uma margem de 10%, o orçamento total para o projeto em 17 semanas é:
```

2023-04-25 10:53 UTC, AlineLermen commented on docs/plano-custos.md
> +Segundo dados de 2021 da [cultura uol](https://cultura.uol.com.br/noticias/26097_6-maneiras-de-economizar-na-conta-de-luz-do-home-office.html) [3], um notebook consome em média cerca de 65W/h, conect
Aqui também 

```suggestion
Segundo dados de 2021 da [cultura uol](https://cultura.uol.com.br/noticias/26097_6-maneiras-de-economizar-na-conta-de-luz-do-home-office.html) [3], um notebook consome em média cerca de 65W/h, conectado ao carregador. Consideramos que cada integrante da equipe trabalhará 4 horas por semana em sua residência, ao longo de 17 semanas. Utilizando esses dados para cálculo, temos:
```

2023-04-25 13:35 UTC, mibasFerraz commented
Ambas sinalizações foram corrigidas

2023-04-25 13:53 UTC, AlineLermen approved these changes

2023-04-26 19:16 UTC, JPedroCh approved these changes

2023-04-26 19:37 UTC, merged